version: "3.8"

services:
  create-service:
    build: ./create-service
    container_name: create-service
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - BASE_URL=http://localhost:3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  redirect-service:
    build: ./redirect-service
    container_name: redirect-service
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - BASE_URL=http://localhost:3002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
